### ISSUE TITLE
Mode Encrypted  don't work correctly

### ISSUE THREAD

**Issue by Jeremi360** [MatiasVME/Persistence#2]
I try use your addon in my [Ren](https://github.com/jeremi360/Ren) Project.
And very thing work ok in "Mode Text", but when I switch to "Mode Encrypted" I get this:
```
[PersistenceNode] Se a cargado el archivo con éxito:   
[PersistenceNode] El archivo no existe: user://Ren/default.save  
[PersistenceNode] load_profile_default retorna false.
```
It seems that in Mode Encrypted I can only save/load *default.save*.

**Comment by MatiasVME** [comment]
Hi, there. Thanks for using my plugin :)

What happens is that the encrypted mode creates a default.save file and the text mode creates a default.txt file.

They are different files and the data from default.txt to default.save is not copied. They are only created again, with new data.

I haven't put that feature on yet.

I will take a look at your project to see how it is using PersistenceNode. To see if something's wrong.

If that's not the problem, please tell me.

**Comment by MatiasVME** [comment]
Also say that. If you are using profile. You must load the profile as follows:

var data = Persistence.get_data("MyProfile")

and to save, it should look like this:

Persistence.save_data("MyProfile")

Anything you tell me.

**Comment by MatiasVME** [comment]
You could try changing line 205:

![screenshot_20180529_153810](https://user-images.githubusercontent.com/342117/40681175-695e178c-6356-11e8-852b-b62db494e0db.png)

```gdscript
# get the data from the profile (MyProfile.txt or MyProfile.save)
var data = Persistence.get_data("MyProfile")

# get the data from the default profile (default.txt or default.save)
var data = Persistence.get_data() 
```

And it is not necessary to use Persistence.load_data()

Just use:
Persistence.get_data() # or Persistence.get_data("profile") 

load_data() is supposed to be private.

**Comment by Jeremi360** [comment]
Okey, thanks for help I will try It.

**Comment by Jeremi360** [comment]
Probably it works, but I can't make first ` Persistence.save_data(profile)` on *Mode Encrypted*.
Can I some how change data in Persistence with out using `get_data(profile)` - `get_data()` don't work.
And also now debug don't work.

**Comment by MatiasVME** [comment]
Mmmm... I don't know if I understand correctly. (My English is bad)

But if you don't want to use get_data() repeatedly. You can do something like that:

In an autoload always have the data:

```gdscript
var recurrent_data = Persistence.get_data(profile)
```

Then from anywhere in your game you could do the following:

```gdscript
my_autoload.recurrent_data["NewData"] = "Some"
Persistence.save_data(profile) # You only need to save after editing
```
______________

And the encryption mode does not show data to avoid exposing it as it is for production. Anyway, you can use, to see the data, something like that: 

```gdscript
print(my_autoload.recurrent_data)
```

I hope I can help. If I didn't answer correctly I could repeat the question differently, please.

_____________

Also say that I have used this plugin in some projects and I have had no problems. Here a minimal example:

```gdscript
extends Node

func _ready():
	# Test: MODE_ENCRYPTED | algo.save | Other folder
	#
	
	Persistence.set_mode(Persistence.MODE_ENCRYPTED)
	Persistence.set_folder_name("OtherFolder")
	print("get_mode(): ", Persistence.get_mode())
	
	var data = Persistence.get_data("algo")
	print("get_data(): ", data)
	
	data["Diccionario"] = {
		Data1x = "Value1x",
		Data2x = "Value2x"
	}
	data["Nuevo2"] = "Nueva Datax2"
	
	Persistence.save_data("algo")
	print("save_data(): ", data)
```

**Comment by MatiasVME** [comment]
Can you give me indications to test your project and see if there is a problem?

**Comment by MatiasVME** [comment]
I found a bug:

```gdscript
func _ready():
	# Test: MODE_TEXT | change profile
	#
	
	Persistence.set_folder_name("ChangeProfile")
	
	Persistence.set_mode(Persistence.MODE_TEXT)
	
	var xx1 = Persistence.get_data("xx1")
	xx1["xx1data"] = "algo1"
	print("xx1: ", xx1)
	Persistence.save_data("xx1")
	
	var xx2 = Persistence.get_data("xx2")
	xx2["xx2data"] = "algo2"
	print("xx2: ", xx2)
	Persistence.save_data("xx2")
```

Result:

```
[PersistenceNode] El archivo no existe: user://ChangeProfile/xx1.txt  
xx1: (xx1data:algo1)
[PersistenceNode] _on_saved()  
______________- JSON -______________
{
	"xx1data": "algo1"
}
____________________________________
[PersistenceNode] El archivo no existe: user://ChangeProfile/xx2.txt  
xx2: (xx1data:algo1), (xx2data:algo2)
[PersistenceNode] _on_saved()  
______________- JSON -______________
{
	"xx1data": "algo1",
	"xx2data": "algo2"
}
```

When you change the profile, the data from profile 1 goes to profile 2.

Let's hope that's the mistake, I'm going to testify for a while and then I'm going to push.

**Comment by Jeremi360** [comment]
https://github.com/jeremi360/Ren/invitations

**Comment by MatiasVME** [comment]
Now i'ts working
