### ISSUE TITLE
Falla al verificar si un valor existe

### ISSUE THREAD

**Issue by zkmark** [MatiasVME/Persistence#5]
Falla al verificar si un valor existe
Error Invalid get index 'pruebas' (on base: 'Dictionary').

	var data = $MainPersistence.get_data("MiProfile") 

	# No te olvides de guardar en disco
	#$MainPersistence.save_data("MiProfile")
	
	if data["pruebas"]:
		print('Existe')

**Comment by MatiasVME** [comment]
Se reescribió el plugin para la versión 4 de godot, cierro el issue, si sigue pasando volver a abrir..
